# Generated by Django 3.1.5 on 2022-09-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms', '0010_auto_20210330_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6),
        ),
    ]
