# Generated by Django 3.1.5 on 2022-09-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtms', '0014_auto_20220913_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6),
        ),
    ]
